### PR TITLE
FSK DB VIEW: select all feature

### PR DESCRIPTION
**Pull request by ahmadswaid**
https://github.com/RakipInitiative/ModelRepository/issues/340
https://github.com/RakipInitiative/ModelRepository/issues/343

### CODE REVIEW

**Comment by schuelet** [comment]
@ahmadswaid a few issues:
- filtering for a subset of models -> select all -> all models, including those not shown after filtering, are selected(true)
- option to select max number of models is still between 2 and 4 (I can live with that though)
- performance is very slow, FSK-Web endpoint (>400 models) crashes when using select-all checkbox

The use-case is to search  for gropin models in landingpage/FSK-Web/ and select them all, without the other models

**Comment by ahmadswaid** [comment]
> @ahmadswaid a few issues:
> 
>     * filtering for a subset of models -> select all -> all models, including those not shown after filtering, are selected(true)
> 
>     * option to select max number of models is still between 2 and 4 (I can live with that though)
> 
>     * performance is very slow, FSK-Web endpoint (>400 models) crashes when using select-all checkbox
> 
> 
> The use-case is to search for gropin models in landingpage/FSK-Web/ and select them all, without the other models
regarding the first point, I was preparing a solution in another PR, I'll cancel it and add it to the current PR.
second point, these setting is only used in the joiner component.

**Comment by ahmadswaid** [comment]
@schuelet: fixed performance issue and selection of filtered rows only if filter is applied.
please have another review.

**Review by schuelet — APPROVED** [review]
great

**Pull request merged**
