### PR TITLE
fix a bug in editing reference dialog

### PR DESCRIPTION
**Pull request by ahmadswaid**
https://github.com/RakipInitiative/ModelRepository/issues/296

### CODE REVIEW

**Review by schuelet — CHANGES_REQUESTED** [review]
@ great job. I noticed an issue though: 
1. the checkbox "is reference" seems to be applied for the entire array, i.e. the last checkbox value is used for all entries. If I edit 2 references an give "true" to reference 1 and "false" to reference 2, then both are "false" after saving.
2. Please remove the function removeUndefinedFromJson, since it seems no longer be necessary and might mess up saving the array. Thanks.

**Review by schuelet — CHANGES_REQUESTED** [review]
@ahmadswaid I still have the problem that you can't edit more than one reference. Is this property cursed?
editor_original

editor_modified

portobject_modified

**Comment by ahmadswaid** [comment]
@schuelet, sorry for going back and forth, It's seems that using `splice` then `push` functions a new row doesn't work as promised.
I use only `splice` to remove and add an item in one statment and that worked fine for reference and parameter and other list.

**Review by schuelet — APPROVED** [review]
@ahmadswaid great job, it works

**Pull request merged**
