### PR TITLE
V2.0 release candidate/ deprecate v1.9

### PR DESCRIPTION
**Pull request by ahmadswaid**
- code base of the moved 1.9 version was https://github.com/SiLeBAT/FSK-Lab/tree/1.9.0-icpmf
- code is moved with some changes espcially after removing FSKplugin and replace it with FskPluginObjectMapper
- FskService design was changed using singlton pattern.
- version 2.0 was added instead the deprecatd 1.9

### CODE REVIEW

**Comment by ahmadswaid** [comment]
@miguelalba @schuelet the testing from my side still in progress but I don't think I will make any big change any more.
you can have a look to the current state and tell me if you find any other issues in your testing.

**Comment by miguelalba** [comment]
Hi @ahmadswaid. I am busy today until 5pm.

**Comment by schuelet** [comment]
Hi @AhmadrSwaid , great job. I have 2 questions: did you take the most recent code from development for the 2.0 nodes? Eclipse makes  it impossible to compare. Just want to make sure, the fixes from the past few days are not overwritten.
Also, in the plugin.xml (Runtime) it says v2_0.runner is an exported package. Why only the runner node?

image

**Comment by ahmadswaid** [comment]
> Hi @ahmadswaid , great job. I have 2 questions: did you take the most recent code from development for the 2.0 nodes? Eclipse makes it impossible to compare. Just want to make sure, the fixes from the past few days are not overwritten.
> Also, in the plugin.xml (Runtime) it says v2_0.runner is an exported package. Why only the runner node?
> 
> image

Hi @schuelet
- yes the new v2.0 node project has the most recent changes from development branch/ i merged the development branch in this branch just yesterday late night.
- regarding the exported packages, this one inhereted from the development branch as well. if it's matter I can investigate which plugin is importing it to be exported.

**Comment by schuelet** [comment]
@ahmadswaid great, thanks. And if the state was the same in the previous version then we shouldn't touch it.

**Comment by schuelet** [comment]
Another question: Is there a way I can save my test workflows that I wrote while the nodes were still called 1_9 ? Just asking for advice, you don't need to do anything.

**Comment by schuelet** [comment]
Tested installation on Windows & Linux and run old and new workflows without any issues (that weren't already there).

**Review by miguelalba — DISMISSED** [review]
Fine for now. I am testing with workflows.

I am getting errors when loading a workflow with a deprecated joiner.
```
ERROR FSK Joiner (deprecated) 0:17       Error loading internals: String for key "firstModelName" not found.
ERROR FSK Joiner (deprecated) 0:26       Error loading internals: String for key "firstModelName" not found.
ERROR FSK Joiner (deprecated) 0:24       Error loading internals: String for key "firstModelName" not found.
ERROR FSK Joiner (deprecated) 0:34       Error loading internals: String for key "firstModelName" not found.
ERROR FSK Joiner (deprecated) 0:39       Error loading internals: String for key "firstModelName" not found.
DEBUG WorkflowManager                 Loaded workflow from "/Users/malba/knime-workspace/Test_Comb_Models_Chain"  with errors
ERROR LoadWorkflowRunnable            Errors during load: Status: Error: Test_Comb_Models_Chain 0 loaded with errors
ERROR LoadWorkflowRunnable              Status: Error: Test_Comb_Models_Chain 0
ERROR LoadWorkflowRunnable                Status: Error: Unable to insert connection "[32(1) -> 34( 3)]"
ERROR LoadWorkflowRunnable                Status: Error: Unable to insert connection "[37(1) -> 39( 3)]"
ERROR LoadWorkflowRunnable                Status: Error: Unable to insert connection "[22(1) -> 26( 3)]"
ERROR LoadWorkflowRunnable                Status: Error: Unable to insert connection "[7(1) -> 17( 3)]"
```

The connections are between an editor and a joiner. This is the trace in Eclipse for each error:
```
ERROR	 ModalContext AbstractWizardNodeModel	 Error loading internals: String for key "firstModelName" not found.
org.knime.core.node.InvalidSettingsException: String for key "firstModelName" not found.
	at org.knime.core.node.config.base.ConfigBase.getString(ConfigBase.java:405)
	at de.bund.bfr.knime.fsklab.v1_9.joiner.JoinerViewRepresentation.loadFromNodeSettings(JoinerViewRepresentation.java:183)
	at org.knime.js.core.node.AbstractWizardNodeModel.loadInternals(AbstractWizardNodeModel.java:365)
	at org.knime.core.node.Node.loadDataAndInternals(Node.java:485)
	at org.knime.core.node.Node.load(Node.java:321)
	at org.knime.core.node.workflow.NativeNodeContainer.performLoadContent(NativeNodeContainer.java:815)
	at org.knime.core.node.workflow.SingleNodeContainer.loadContent(SingleNodeContainer.java:783)
	at org.knime.core.node.workflow.WorkflowManager.postLoad(WorkflowManager.java:7881)
	at org.knime.core.node.workflow.WorkflowManager.loadContent(WorkflowManager.java:7756)
	at org.knime.core.node.workflow.WorkflowManager.postLoad(WorkflowManager.java:7881)
	at org.knime.core.node.workflow.WorkflowManager.loadContent(WorkflowManager.java:7756)
	at org.knime.core.node.workflow.WorkflowManager.load(WorkflowManager.java:7710)
	at org.knime.core.node.workflow.WorkflowManager.load(WorkflowManager.java:7631)
	at org.knime.core.node.workflow.WorkflowManager.load(WorkflowManager.java:7604)
	at org.knime.core.node.workflow.WorkflowManager.loadProject(WorkflowManager.java:7449)
	at org.knime.workbench.editor2.LoadWorkflowRunnable.run(LoadWorkflowRunnable.java:176)
```

@schuelet and @ahmadswaid is this normal?

**Comment by ahmadswaid** [comment]
> Fine for now. I am testing with workflows.
> 
> I am getting errors when loading a workflow with a deprecated joiner.
> 
> ```
> ERROR FSK Joiner (deprecated) 0:17       Error loading internals: String for key "firstModelName" not found.
> ERROR FSK Joiner (deprecated) 0:26       Error loading internals: String for key "firstModelName" not found.
> ERROR FSK Joiner (deprecated) 0:24       Error loading internals: String for key "firstModelName" not found.
> ERROR FSK Joiner (deprecated) 0:34       Error loading internals: String for key "firstModelName" not found.
> ERROR FSK Joiner (deprecated) 0:39       Error loading internals: String for key "firstModelName" not found.
> DEBUG WorkflowManager                 Loaded workflow from "/Users/malba/knime-workspace/Test_Comb_Models_Chain"  with errors
> ERROR LoadWorkflowRunnable            Errors during load: Status: Error: Test_Comb_Models_Chain 0 loaded with errors
> ERROR LoadWorkflowRunnable              Status: Error: Test_Comb_Models_Chain 0
> ERROR LoadWorkflowRunnable                Status: Error: Unable to insert connection "[32(1) -> 34( 3)]"
> ERROR LoadWorkflowRunnable                Status: Error: Unable to insert connection "[37(1) -> 39( 3)]"
> ERROR LoadWorkflowRunnable                Status: Error: Unable to insert connection "[22(1) -> 26( 3)]"
> ERROR LoadWorkflowRunnable                Status: Error: Unable to insert connection "[7(1) -> 17( 3)]"
> ```
> 
> The connections are between an editor and a joiner. This is the trace in Eclipse for each error:
> 
> ```
> ERROR	 ModalContext AbstractWizardNodeModel	 Error loading internals: String for key "firstModelName" not found.
> org.knime.core.node.InvalidSettingsException: String for key "firstModelName" not found.
> 	at org.knime.core.node.config.base.ConfigBase.getString(ConfigBase.java:405)
> 	at de.bund.bfr.knime.fsklab.v1_9.joiner.JoinerViewRepresentation.loadFromNodeSettings(JoinerViewRepresentation.java:183)
> 	at org.knime.js.core.node.AbstractWizardNodeModel.loadInternals(AbstractWizardNodeModel.java:365)
> 	at org.knime.core.node.Node.loadDataAndInternals(Node.java:485)
> 	at org.knime.core.node.Node.load(Node.java:321)
> 	at org.knime.core.node.workflow.NativeNodeContainer.performLoadContent(NativeNodeContainer.java:815)
> 	at org.knime.core.node.workflow.SingleNodeContainer.loadContent(SingleNodeContainer.java:783)
> 	at org.knime.core.node.workflow.WorkflowManager.postLoad(WorkflowManager.java:7881)
> 	at org.knime.core.node.workflow.WorkflowManager.loadContent(WorkflowManager.java:7756)
> 	at org.knime.core.node.workflow.WorkflowManager.postLoad(WorkflowManager.java:7881)
> 	at org.knime.core.node.workflow.WorkflowManager.loadContent(WorkflowManager.java:7756)
> 	at org.knime.core.node.workflow.WorkflowManager.load(WorkflowManager.java:7710)
> 	at org.knime.core.node.workflow.WorkflowManager.load(WorkflowManager.java:7631)
> 	at org.knime.core.node.workflow.WorkflowManager.load(WorkflowManager.java:7604)
> 	at org.knime.core.node.workflow.WorkflowManager.loadProject(WorkflowManager.java:7449)
> 	at org.knime.workbench.editor2.LoadWorkflowRunnable.run(LoadWorkflowRunnable.java:176)
> ```
> 
> @schuelet and @ahmadswaid is this normal?

@miguelalba  No it should not. I tried all the workflow shared from @schuelet and didn't received this error.
please share the workflow to investgate.

**Comment by schuelet** [comment]
@miguelalba and @ahmadswaid Those workflows were created with the delevopment branch, when the nodes were still called 1_9. I updated the workflows already on the KNIME server. Here is the chain wf:
[Test_Comb_Models_Chain.zip](https://github.com/SiLeBAT/FSK-Lab/files/6085235/Test_Comb_Models_Chain.zip)

**Comment by miguelalba** [comment]
Ok. Then fine by me.

**Review by schuelet — APPROVED** [review]

**Comment by ahmadswaid** [comment]
@miguelalba still can't merge as I'm still reuested to do a change which you already revoke!

**Pull request merged**
