### PR TITLE
fixing simulation scenarios generation

### PR DESCRIPTION
**Pull request by ahmadswaid**
https://github.com/RakipInitiative/ModelRepository/issues/275
https://github.com/RakipInitiative/ModelRepository/issues/274

### CODE REVIEW

**Comment by schuelet** [comment]
@ahmadswaid Thanks, it does work. However I am concerned that the first simulation is no longer called "defaultSimulation", not sure if it could break some node down the line. Do you think it is safe enough?

**Comment by ahmadswaid** [comment]
@schuelet:  I don't think unsafe, but I will not take the risk. the simulation generated of "defaultsimulation"s is "defaultsimulation" from now on.

**Comment by ahmadswaid** [comment]
@schuelet: Do you think you can reolve this PR?

**Review by schuelet — APPROVED** [review]
@ahmadswaid apologies, the PR showed no update on the "Pull requests" main page.

**Pull request merged**
