### PR TITLE
Fix bug that modal is always on top of component view

### PR DESCRIPTION
**Pull request by ahmadswaid**
https://github.com/RakipInitiative/ModelRepository/issues/354

### CODE REVIEW

**Comment by schuelet** [comment]
@ahmadswaid: I like your solution because it is simple and won't break any of the business logic. However, by auto-scrolling to the top of the page we run into trouble when we have other JS-Views in the Component (e.g. the Joiner on top and DBView on bottom). Is there a way to catch this case (multiple views)?

**Comment by ahmadswaid** [comment]
@schuelet done, please review it. rebuild of JS module is required!

**Comment by schuelet** [comment]
@ahmadswaid : Only works the first time I click on the details button. After that, the view is all over the place. Each time I move the mouse or click someplace, the vertical scrollbar slider freaks out.

**Review by schuelet — APPROVED** [review]
@ahmadswaid All clear. Thanks a lot!

**Pull request merged**
