### PR TITLE
fix https://github.com/RakipInitiative/ModelRepository/issues/276

### PR DESCRIPTION
**Pull request by ahmadswaid**
https://github.com/RakipInitiative/ModelRepository/issues/276

### CODE REVIEW

**Review by schuelet — CHANGES_REQUESTED** [review]
Doesn't seem to work on Windows. Used the joiner_doesnt_add_simulations workflow.
`ERROR` FSKX Reader          0:35       Execute failed: Illegal char <:> at index 74: C:/Users/thsch/AppData/Local/Temp/knime_joiner_doesnt_a47845/FSKX Reader 0:35.fskx`

Also, getDownloadedFileName() seems unsafe, if the Reader is wrapped in a componend or metanode, it might screw up the path. Not sure though. I am also not sure if the File.separator would make sharing workflows between different systems impossible, since the environment manager looks for the path, but I could live with that for now.

**Comment by schuelet** [comment]
The colon (":") was the problem, adding .replaceAll(":", "_") seems to solve the issue. 
However, 
- upon saving and reloading the wf, the temp archive is gone.
- wrapping in a metanode does not make the Runner fail, so that is not an issue after all.

**Comment by schuelet** [comment]
I propose to just save the archive in the just in the workflow folder, maybe take the model id to name it, that would remove the chance to have duplicates if other reader nodes attempt to download the same model. It would also remove the issue (i hope) with sharing the wf across different OS.

**Comment by ahmadswaid** [comment]
@schuelet can't use model ID as a name since we don't have it yet before downloading.

**Review by schuelet — APPROVED** [review]

**Pull request merged**
