### PR TITLE
added footer with EFSA disclaimers

### PR DESCRIPTION
**Pull request by schuelet**
@ahmadswaid On the landingpage the footer is sticky but it doesn't seem to work in the DBView on my local machine.

### CODE REVIEW

**Comment by ahmadswaid** [comment]
@schuelet part of the text doen't appear on smaller screen, I needed to make window full screen to check what is written:
image

**Comment by schuelet** [comment]
@ahmadswaid I think I fixed that now.

**Comment by ahmadswaid** [comment]
sorry, but making the window smalller by draging stilll show  the same problem

**Comment by schuelet** [comment]
@ahmadswaid OK, could you check again, please? Thx.

**Comment by ahmadswaid** [comment]
@schuelet I think the issue of responsive design is still there for sizes like 2.8 inches width and less, also I don't know if you want to have the footer to be shown on the simulator JS and in the the Editor JS?

**Pull request closed without merging**
