### PR TITLE
Editor bug picking a model from configuration dropdown menu fails node

### PR DESCRIPTION
**Pull request by ahmadswaid**
https://github.com/RakipInitiative/ModelRepository/issues/304
- the NPM is caused by missing ModelMath in all model except generic model.
- this PR applies conversion utils to convert models from one model provided via port, this is usefull when connecting one node with some model type with another node and selecting another model type 
- also this conversion is applied on nodes with saved model metadata via `save as default or temporarily` which setup with a new model type.

### CODE REVIEW

**Comment by schuelet** [comment]
Hi @ahmadswaid : I found some issues: 
- on changing to dose-response model in configuration dropdown menu:
- model name is mising, even if a new name is given and saved, on reopening view, model name is gone
- scripts are missing
- if nothing is done at all, i.e. editor is just executed -> reset -> execute and open view: node error

workflow avaliable: knime://external-KNIME-Server/FSKX_Testing/FSK-Lab_2.0/broken_workflows/editor_Test_change_Model_Type

**Comment by ahmadswaid** [comment]
> Hi @ahmadswaid : I found some issues:
> 
>     * on changing to dose-response model in configuration dropdown menu:
> 
>     * model name is mising, even if a new name is given and saved, on reopening view, model name is gone
> 
>     * scripts are missing
> 
>     * if nothing is done at all, i.e. editor is just executed -> reset -> execute and open view: node error
> 
> 
> workflow avaliable: knime://external-KNIME-Server/FSKX_Testing/FSK-Lab_2.0/broken_workflows/editor_Test_change_Model_Type

I noticed the model name issue but forget to put it in the description. It's an issue in the YAML file itself
some model has generalInformation => modelName
an some has generalInformation => name

**Comment by ahmadswaid** [comment]
> Hi @ahmadswaid : I found some issues:
> 
>     * on changing to dose-response model in configuration dropdown menu:
> 
>     * model name is mising, even if a new name is given and saved, on reopening view, model name is gone
> 
>     * scripts are missing
> 
>     * if nothing is done at all, i.e. editor is just executed -> reset -> execute and open view: node error
> 
> 
> workflow avaliable: knime://external-KNIME-Server/FSKX_Testing/FSK-Lab_2.0/broken_workflows/editor_Test_change_Model_Type

- I can reproduce and fixed the missing scripts after conversion in https://github.com/SiLeBAT/FSK-Lab/pull/856/commits/ac0fadf1802af13dd60625b5f6ba560384b1feee
- I can't reproduce the fouth point could you please double check.

**Comment by schuelet** [comment]
> * I can't reproduce the fouth point could you please double check.
@ahmadswaid Yes I double checked, and executing (without opening view) **twice** leads to an NPE because the model type in m_config is not set:
image

**Comment by ahmadswaid** [comment]
> > * I can't reproduce the fouth point could you please double check.
> >   @ahmadswaid Yes I double checked, and executing (without opening view) **twice** leads to an NPE because the model type in m_config is not set:
> >   image

@schuelet : Sorry you're right, now with https://github.com/SiLeBAT/FSK-Lab/pull/856/commits/b97e034c47f653bfd8fcc9a835d601d48b427528 it should be fixed

**Comment by schuelet** [comment]
@ahmadswaid Now, on opening and saving the editor fails: 
image

**Comment by ahmadswaid** [comment]
> @ahmadswaid Now, on opening and saving the editor fails:
> image

that's becase modeltype in configuration has value `GenericModel` and the one from the metadata of the input port object has value`genericModel` 
@schuelet please have another review

**Review by schuelet — APPROVED** [review]

**Pull request merged**
