### PR TITLE
Continuous delivery of JSON schema From model.yaml(SPOT)

### PR DESCRIPTION
**Pull request by ahmadswaid**
The goal here is generate the JSON schema automaticaly from the YAML.
No manual generation is needed and any update in the YAML Schema will be reflected in the JS side via the generated JSON schema.
related to: https://github.com/SiLeBAT/FSK-Lab/pull/849

### CODE REVIEW

**Comment by schuelet** [comment]
Hi @ahmadswaid : how can I best test if it is working?

**Comment by schuelet** [comment]
de.bund.bfr.knime.js/specs/template.js

 @ahmadswaid is the code here correct? It just says: 
`de.bund.bfr.knime.js/specs/template.js`

**Comment by ahmadswaid** [comment]
@schuelet make a local build and start knime => create a new editor and save to check the validation. if you recieve the validation, that means you have the schema generated and it's in use

**Comment by ahmadswaid** [comment]
> de.bund.bfr.knime.js/specs/template.js
> 
> @ahmadswaid is the code here correct? It just says:
> `window.modelSchema = `

it's correct,  It's used in the grunt file to concat it with the generated JSON schema from the YAML one to have the schema as a global variable in the app.build.js

**Comment by schuelet** [comment]
@ahmadswaid ok I did that. On opening an empty editor and saving I get some warnings:
image

Model Name is curiously absent, but I guess the id (UUID) is enough. So it seems to work, good job.

**Review by schuelet — APPROVED** [review]

**Comment by ahmadswaid** [comment]
> @ahmadswaid ok I did that. On opening an empty editor and saving I get some warnings:
> image
> 
> Model Name is curiously absent, but I guess the id (UUID) is enough. So it seems to work, good job.

It's not missed, it's there but called `name`

**Pull request merged**
