### PR TITLE
fix https://github.com/RakipInitiative/ModelRepository/issues/335

### PR DESCRIPTION
**Pull request by ahmadswaid**
https://github.com/RakipInitiative/ModelRepository/issues/335

### CODE REVIEW

**Comment by schuelet** [comment]
@ahmadswaid Sorry it takes so long, but I need more time testing. 
I get an issue when loading a model and just execute the editor without opening it. It seems, the output parameters are included in the simulation.

**Comment by ahmadswaid** [comment]
> @ahmadswaid Sorry it takes so long, but I need more time testing.
> I get an issue when loading a model and just execute the editor without opening it. It seems, the output parameters are included in the simulation.

@schuelet good catch.

**Comment by schuelet** [comment]
@ahmadswaid Found another bug: If there is another simulation present, the second one has the value of the defaultSimulation.

**Comment by ahmadswaid** [comment]
> @ahmadswaid Found another bug: If there is another simulation present, the second one has the values of the defaultSimulation.

@schuelet sorry, everything should be correct by now

**Review by schuelet — APPROVED** [review]

**Pull request merged**
